Fix TypeError raised by str(HSP()) (#2208)
`TypeError` is raised if you try to print an uninitialized `HSP` instance:

```python
>>> from Bio.Blast.Record import HSP
>>> str(HSP())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../site-packages/Bio/Blast/Record.py", line 227, in __str__
    % (self.score, self.bits, self.expect, self.align_length)]
TypeError: %i format: a number is required, not NoneType
```

Fix __str__ when align_length is None

Add test case for HSP.__str__

Add fmt_() helper to print values that may be None

Also, add docstring