Fix DSSP error when MMCIF file contains non-standard residues (#1194)
When running DSSP on the newer PDBx/mmCIF file format, the following error is observed when the structure contains non-standard residues (e.g. 1AS5.cif structure):

Bio.PDB.PDBExceptions.PDBException: Structure/DSSP mismatch at <Residue HYP het= resseq=2 icode= >

This is due to DSSP labelling any non-standard residues as X, whereas DSSP.py checks against a much larger dictionary of possible residue 3-letter codes (SCOPData.protein_letters_3_to_1). For example, the residue HYP gets interpreted as P, whereas DSSP returns this as X.

Using the old PDB file format, these sorts of residues would be labelled as HETATOM, and hence get caught earlier in the DSSP.py code, but this isn't the case with mmCIF files.

I'm proposing a simple change where anything that isn't a standard residue gets interpreted as X.

I've added the relevant unit tests to test DSSP generation on mmCIF files that contain non-standard residues.