Fix byte mode detection on `BgzfWriter`
In commit c4a47ffff7f3e7de32ab3d8846983d3531ea63b4, there was an
attempt to detect handles which are not in binary mode. However, there's
a core problem here in that most handles open in write mode *cannot* be
read from. For example:

```python
>>> handle = open('/tmp/demo.txt', 'wb')
>>> handle.read(0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
io.UnsupportedOperation: read
```

This means that one cannot pass a plain writeable file object to
`BgzfWriter`:

```python
>>> Bio.__version__
'1.83'
>>> Bio.bgzf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'Bio' has no attribute 'bgzf'
>>> from Bio import bgzf
>>> with open('/tmp/demo.txt', 'wb') as handle:
...     bgzf.BgzfWriter(fileobj=handle)
...
    if fileobj.read(0) != b"":
       ^^^^^^^^^^^^^^^
io.UnsupportedOperation: read
```

If eager detection of the handle's mode is desired, one can check
`handle.mode` as was done before -- I opt here to just hardcode handling
of `io.StringIO`. The simplest option in my opinion is to just rely on
ducktyping -- the `_write_block()` method will try to write the data --
either the handle accepts `bytes` and all is well, or it fails.