Downgrade sphinx to confirm conf.py regression
Calling sphinx-apidoc via conf.py broke on Sphinx 1.7.1,

$ make SPHINXBUILD=python -msphinx -W -C Doc/api/ html
make: Entering directory `/home/travis/build/biopython/biopython/Doc/api'
python -msphinx -W -b html -d _build/doctrees   . _build/html
Running Sphinx v1.7.1
loading translations [en]... done
making output directory...
loading pickled environment... not yet created
usage: usage: __main__.py [OPTIONS] -o <OUTPUT_PATH> <MODULE_PATH> [EXCLUDE_PATTERN, ...]
__main__.py: error: argument -d/--maxdepth: invalid int value: '_build/doctrees'
make: *** [html] Error 2
make: Leaving directory `/home/travis/build/biopython/biopython/Doc/api'
ERROR: InvocationError: '/usr/bin/make SPHINXBUILD=python -msphinx -W -C Doc/api/ html'