Remove now unused import
This was used in the recently removed self-test, see #1930.

However, rather than triggering an unused import, we seem to
have triggered a flake8 false positive where range is defined as
a class method:

$ flake8 Bio/
Bio/Graphics/GenomeDiagram/_Track.py:226:5: F811 redefinition of unused 'range' from line 27