Fix for numpy 2.2 testing truth of empty arrays
ValueError: The truth value of an empty array is ambiguous. Use  to check that an array is not empty.

Using bool(empty_array) was deprecated, and became an error in numpy 2.2.0.