Added example to xpktools with the example file Doc/examples/nmr/noed.xpk. Doing so uncovered a bug in line 64 (orig) where the variable line wasn't updated. Attempting to add an example to predictNOE complained that variable detectedList was referenced before assignment, showing that the check for the two keys in the data file failed, even using the recommended examples, H1 and N15. I'm unsure of whether this is useful to squash, since its out of the scope of the doc-porting project?
the code that failed:

import NOEtools
prediction = NOEtools.predictNOE(xpktools.Peaklist('../../Doc/examples/nmr/noed.xpk'), 'H1', 'N15',10,12)
Traceback (most recent call last):
  File <stdin>, line 1, in <module>
  File NOEtools.py, line 72, in predictNOE

UnboundLocalError: local variable 'detectedList' referenced before assignment