Tell flake8 to ignore redefinition in Bio/pairwise2.py
Bio/pairwise2.py:990:5: F811 redefinition of unused 'rint' from line 886
Bio/pairwise2.py:990:5: F811 redefinition of unused '_make_score_matrix_fast' from line 549