Close index handles in SeqIO doctests
Tested as follows:

$ python3.4 -W all run_tests.py doctest
Python version: 3.4.0a4 (default, Nov  4 2013, 14:58:04)
[GCC 4.2.1 Compatible Apple LLVM 5.0 (clang-500.2.79)]
Operating system: posix darwin
Bio.Align docstring test ... ok
...
Bio.SeqIO docstring test ... ok
...

Unfortunately the short trick no longer works:

$ python Bio/SeqIO/__init__.py
Traceback (most recent call last):
  File Bio/SeqIO/__init__.py, line 358, in <module>
    from . import AbiIO
ValueError: Attempted relative import in non-package

$ python3.4 Bio/SeqIO/__init__.py
Traceback (most recent call last):
  File Bio/SeqIO/__init__.py, line 358, in <module>
    from . import AbiIO
SystemError: Parent module '' not loaded, cannot perform relative import