Remove __slots__ in Bio.Nexus
This fixes a problem under Python 3.3.0 (tested on Mac OS X),

$ python3 test_Nexus.py
Traceback (most recent call last):
  File test_Nexus.py, line 7, in <module>
    from Bio.Nexus import Nexus, Trees
  File /Users/peterjc/lib/python3.3/site-packages/Bio/Nexus/Nexus.py, line 513, in <module>
    class Nexus(object):
ValueError: 'original_taxon_order' in __slots__ conflicts with class variable

It appears not to break any of the unit tests under Python 2,
will flag this on the mailing list for discussion just in case...