Upgrade pip before setuptools and wheel.
Hopefully fixes this failure trying to use get_runnable_pip which is
only a very recent addition to pip:

ImportError: cannot import name 'get_runnable_pip' from 'pip._internal.utils.misc' (/opt/hostedtoolcache/Python/3.14.6/x64/lib/python3.14/site-packages/pip/_internal/utils/misc.py)