Be more forgiving in SQLite3 tests about removing temp files
e.g.

WindowsError: [Error 32] The process cannot access the file because it is being used by another process.: c:\temp\tmplvwrcb_BioSQL.db