Can't use the doctest trick anymore due to local import.
$ python2.6 pairwise2.py
Traceback (most recent call last):
  File pairwise2.py, line 990, in <module>
    from .cpairwise2 import rint, _make_score_matrix_fast
ValueError: Attempted relative import in non-package

$ python3.4 Bio/pairwise2.py
Traceback (most recent call last):
  File Bio/pairwise2.py, line 990, in <module>
    from .cpairwise2 import rint, _make_score_matrix_fast
SystemError: Parent module '' not loaded, cannot perform relative import

etc